name: PHP Composer
env:
  DB_HOST: localhost
  DB_DATABASE: coa
  DB_USER: root
  DB_PASSWORD: root

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2' ]
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Install MariaDB
        uses: ankane/setup-mariadb@v1
        with:
          database: ${{ env.DB_DATABASE }}

      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS
        run: git lfs checkout

      - name: Load database
        run: zcat coa.sql.gz | mysql ${{ env.DB_DATABASE }}
        working-directory: tests/test_data
        shell: bash

      - name: Set MariaDB password
        run: mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${{ env.DB_PASSWORD }}';"

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: pdo_mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3